### ISSUE TITLE
faction

### ISSUE THREAD

**Issue by demon57730** [mffbrokenswing/FactionMod#1]
You can explain how a faction rises in lvl

**Comment by BrokenSwing** [comment]
Sorry for answering lately, to gain experience you have to kill mobs and players. I have to explain it in the documentation. You get experience if : 
- You kill the ender dragon
- You kill a wither skeleton
- You kill a Wither Boss
- You kill a player of an other faction

**Comment by BrokenSwing** [comment]
But this type of question should be asked on the Discord of the mod or on Curse

Curse : https://mods.curse.com/mc-mods/minecraft/272919-faction-mod
Discord : https://discord.gg/yhYqBVF
