### ISSUE TITLE
Chat configuration

### ISSUE THREAD

**Issue by sfxworks** [mffbrokenswing/FactionMod#3]
For our server, we need to be able to hide/configure the way usernames are displayed. We have nucleus, so we are forced to prevent nucleus from adding the name to chat, which in turn prevents nicknames from display in the chat. We need documentation on how to do this. If there is none, can you please add this feature to your mod?

**Comment by BrokenSwing** [comment]
Unfortunately I stopped developing this mod. But feels free to fork it and modify it to fit it to your needs.
