### ISSUE TITLE
Workspace Questions

### ISSUE THREAD

**Issue by TerdyTheTerd** [mffbrokenswing/FactionMod#4]
Its been ages since I've done any Minecraft modding, but I'm looking into it again, and for my needs I was looking into extending this mod. However when setting up the workspace and running it this mod doesn't seem to load. I am unsure if there are any specifics I need (versions, dependencies) or if there have been changes to Forge/Gradle that require a different method (I don't think this is the case as I also setup a workspace for another mod that I forked, and it works just fine).
So the question is: Do I simply clone the repo, run the commands (setupDecompWorkspace eclipse) and open the workspace in Eclipse, or do I need to do anything special?

**Comment by BrokenSwing** [comment]
Hello,
I was unconscious when I created this repo, I didn't provide the gradle wrapper. It should be the only thing missing. After that just run : 
``gradlew setupDecompWorkspace eclipse`` 
And it should work.
If it doesn't, dont hesitate to repost here.
